In [1]:
import pandas as pd

In [11]:
data =[
    ("Bob",100),
    ("Alice",200),
    ("Charlie",300),
    ("David",250),
    ("Elango",150),
    ("Ravi",220),
    ("Praveena",80)
    
]

df = pd.DataFrame(data, columns=["Name","Score"])

In [10]:
df.head()

      Name  Score
0      Bob    100
1    Alice    200
2  Charlie    300
3    David    250
4   Elango    150

In [12]:
df.describe()

            Score
count    7.000000
mean   185.714286
std     79.970233
min     80.000000
25%    125.000000
50%    200.000000
75%    235.000000
max    300.000000